name: pyramids
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  shared_preferences: ^2.5.3
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/egypt_bg.jpg
    - assets/images/AppLogo.png
    - assets/images/branding.png
    - assets/images/AppSplash.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/AppSplash.png
  android: true
  ios: true
  branding: assets/images/branding.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/AppSplash.png
    branding: assets/images/branding.png

  color_dark: "1F1F1F"
  image_dark: assets/images/AppSplash.png
  branding_dark: assets/images/branding.png



flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/AppLogo.png"
  adaptive_icon_background: "#FFFFFF"

